services:
 postgres:
  image: postgres:17
  container_name: de_week3_postgres
  environment:
   POSTGRES_DB: de_week3
   POSTGRES_USER: de_user
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ports: 
   - "5432:5432"
  volumes: 
   - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: